apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:  # Corrected 'lables' to 'labels'
    apps: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:  # Corrected 'matchlables' to 'matchLabels'
      apps: spring-boot-app
  template:
    metadata:
      labels:
        apps: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: abhishekf5/ultimate-cicd:replaceImageTag
          ports:
            - containerPort: 8080  # Corrected 'containerport' to 'containerPort'
