apiVersion: v1
kind: Service
metadata:
  labels:  # Corrected 'lables' to 'labels'
    name: spring-boot-app-service
spec:
  type: NodePort
  ports:
    - name: http  # Added space after '-' and corrected indentation
      port: 80
      targetPort: 8080  # Corrected 'targetport' to 'targetPort'
      protocol: TCP
  selector:
    app: spring-boot-app
