pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('check out') {
      steps{
         sh'echo check out'
      //gitclone
      }
     
    }
    stage('2build') {
      steps {
        //BUILD THE code using maven
        sh 'cd mypipeline/spring-boot-app && mvn clean package'
      }
    }
    
  }
}